package com.cs407.shopsmart;
import androidx.appcompat.app.ActionBar;
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.MenuItem;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.security.SecureRandom;

public class LoginScreen extends AppCompatActivity {

    SharedPreferences loginDatabase;
    SecureRandom randomGen;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login_screen);

        // Shows the nav arrow on top of screen
        ActionBar actionBar = getSupportActionBar();
        actionBar.setDisplayHomeAsUpEnabled(true);

        randomGen = new SecureRandom();
        loginDatabase = getSharedPreferences("loginDatabase", MODE_PRIVATE);
    }

    /**
     * Deals with navigating back by one activity.
     *
     * @param item The menu item that was selected.
     * @return
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item){
        int id = item.getItemId();

        if (id == android.R.id.home){
            navigateUpTo(new Intent(this, HomeLoginScreen.class));
            return true;
        }
        return false;
    }

    /**
     * A helper function that can take in a password, a random salt, and allows the user
     * to hash their password to be placed into the database safely.
     *
     * @param password the users plaintext password
     * @param salt a randomly generated byte array to include with the plaintext password
     * @param iterationCount defaulted to 4096
     * @param keyLength defaulted to 256
     * @return the result of the password+salt, hashed!
     * @throws NoSuchAlgorithmException
     * @throws InvalidKeySpecException
     */
    public static SecretKey pbkdf2(char[] password, byte[] salt, int iterationCount, int keyLength) throws NoSuchAlgorithmException, InvalidKeySpecException {
        SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
        PBEKeySpec spec = new PBEKeySpec(password, salt, iterationCount, keyLength);
        return factory.generateSecret(spec);
    }


}